on:
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        type: string

jobs:
  test:
    uses: ./.github/workflows/run-job-with-params.yml
    secrets: inherit
    with:
      springProfile: 'production'
      logLevel: ${{ inputs.logLevel || 'DEBUG' }}
