name: Mixed inputs with Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        required: true
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: |
          # Add your code here to send a greeting

  build:        
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request branch
      - uses: actions/checkout@v3
      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      # Run the Python script and read user input
      - name: Run Python script
        run: |
          python script.py
